paths:
  raw_data: data/raw
  processed_data: data/processed
  warehouse_data: data/warehouse
  logs: logs

files:
  processed_csv: ssb_construction_cost_index_clean.csv
  duckdb_file: ssb_analytics.duckdb

api:
  source_name: jsonplaceholder
  source_url: https://jsonplaceholder.typicode.com/posts

ssb:
  base_url: https://data.ssb.no/api/v0/en/table
  planned_source: StatBank Norway